<form action="<?= $block->getFormAction() ?>" method="post">
    <?= $block->getBlockHtml('formkey') ?>

    <label>Name:</label>
    <input type="text" name="name" required /><br>

    <label>Description:</label>
    <textarea name="description" required></textarea><br>

    <label>Rating:</label>
    <input type="number" name="rating" step="0.1" /><br>

    <button type="submit" class="action-primary">Save</button>
</form>
